// Components barrel export
export * from './header/header.component';
export * from './hero/hero.component';
export * from './about/about.component';
export * from './experience/experience.component';
export * from './education/education.component';
export * from './skills/skills.component';
export * from './contact/contact.component';
export * from './footer/footer.component';
